### PR TITLE
Version 0.1.78

### PR DESCRIPTION
**Pull request by juliogonzalez**
## What does this PR do?

Push Gem version to Version 0.1.78

### CODE REVIEW

**Comment by MalloZup** [comment]
@juliogonzalez i added you as admin of this repo so you will be able to merge

**Comment by juliogonzalez** [comment]
Thanks @MalloZup

**Comment by juliogonzalez** [comment]
@MalloZup, I am confused.

I just created 0.1.78, but:

```
$ gem push gem/gitarro-0.1.78.gem
Pushing gem to https://rubygems.org...
Repushing of gem versions is not allowed.
Please use `gem yank` to remove bad gem releases.
```
And indeed, 0.1.78 already exists at rubygems.org and it was uploaded months ago!

> VERSIONS:
> 0.1.78 - March 19, 2018 (10.5 KB)
> 0.1.77 - March 16, 2018 (10.5 KB)
> 0.1.76 - March 16, 2018 (10.5 KB)
> 0.1.75 - March 15, 2018 (10.5 KB)
> 0.1.74 - March 13, 2018 (10.5 KB)

**Comment by MalloZup** [comment]
@juliogonzalez  :+1:

**Pull request merged**
