### PR TITLE
changelog_test: Show an error if the environment variables do not exist

### PR DESCRIPTION
**Pull request by juliogonzalez**
## What does this PR do?

changelog_test: Show an error if the environment variables do not exist

### CODE REVIEW

**Comment by MalloZup** [comment]
to gitlab

**Comment by juliogonzalez** [comment]
@MalloZup you mean to infrastructure? Do we use it from there?

**Comment by juliogonzalez** [comment]
Ok, found it, and copied it there.

**Comment by MalloZup** [comment]
@juliogonzalez i forgot it

It might be possible.

To me as really the most cleanst solution would be:

use it in jenkins-ci repo

**Pull request merged**
