### PR TITLE
Hotfix a mistake in params on retriggered_by_comment method

### PR DESCRIPTION
**Pull request by srbarrios**
## What does this PR do?

Hotfix a mistake in params on retriggered_by_comment method.

As we added that method (to include both ways of trigger a test), The signature of the method was changed, so now we are passing the PR and we need then to specify the pr.number for issue_comments method.
```
  def retrigger_needed?(pr)
    # we want redo sometimes tests
    return false unless retriggered_by_checkbox?(pr, @context) ||
                        retriggered_by_comment?(pr, @context)
```

### CODE REVIEW

**Comment by MalloZup** [comment]
@srbarrios  do you have a backtrace of the error?

**Comment by MalloZup** [comment]
i would also like to know why this error popped-up now, since your PR didn't modify that part of code. thx

**Comment by srbarrios** [comment]
> i would also like to know why this error popped-up now, since your PR didn't modify that part of code. thx

Could you connect to IRC a minute please?

**Comment by MalloZup** [comment]
sorry guys, for merging a PR should i connect to  irc? i think we should do it on Github. this is a opensource project.

**Comment by srbarrios** [comment]
> sorry guys, for merging a PR should i connect to irc? i think we should do it on Github. this is a opensource project.

I just wanted to explain you before add the coment, but read the description, is there.

**Comment by MalloZup** [comment]
@srbarrios @juliogonzalez ok thx. JFYI for next-time, try to have a real run locally before we create a broken gem. 

For the rest ok, thx for this fix

**Comment by srbarrios** [comment]
> @srbarrios @juliogonzalez ok thx. JFYI for next-time, try to have a real run locally before we create a broken gem.
> 
> For the rest ok, thx for this fix

Yep, sorry, I did the change at last moment and only run the acceptance tests. Which doesn't catch that issue.

**Comment by MalloZup** [comment]
@srbarrios  no worry, we can all fail. but we should not make it habits. :smiley: 

The tests-acc either need improvements or we need to catch it manually.

Anyways, thx for the fix and the patch. good job

**Comment by juliogonzalez** [comment]
`@srbarrios @juliogonzalez ok thx. JFYI for next-time, try to have a real run locally before we create a broken gem.`

That's what @srbarrios did, but it seems he did not remember when he commited again.

And that's understandable. It can happen to anyone.

Such test should be automated, not manual. Not when we commit, and not when we submit the gem, but at all times. Otherwise each PR can break gitarro.

IIRC, we have something in the past but we removed it in favour of mock tests. Time to bring it back?

**Comment by MalloZup** [comment]
i'm not sure if we have removed something with mocking test.
we might need to check.

**Comment by MalloZup** [comment]
anyways, yes when making change things move so it can happen to anyone. 

opening following up issue about testacc

**Pull request merged**
